name: CI-with-test-to-UI
# on:
#   push:
#     branches:
#       - "main"
on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: registry-ui.portal.staas.ru
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}
  # TEST_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
  # LATEST_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
  # TEST_TAG: registry.portal.staas.ru/igorpex/app:test
  TEST_TAG: registry-ui.portal.staas.ru/igorpex/app:test
  # LATEST_TAG: registry.portal.staas.ru/igorpex/app:latest
  LATEST_TAG: registry-ui.portal.staas.ru/igorpex/app:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          logout: true
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
